apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: {{ .Values.UI_REPLICAS }}
  revisionHistoryLimit: {{ .Values.REVISION_HISTORY_LIMIT }}
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: {{ .Values.UI_IMAGE }}
        name: guestbook-ui
        ports:
        - containerPort: 80
